export type LegalDoc = { slug: string; title: string; body: string };

export const LEGAL_DOCS: LegalDoc[] = [
  {
    slug: "affiliate-disclosure",
    title: "Affiliate Disclosure",
    body: [
      "## Affiliate relationships",
      "PartyPlan recommends products from partner merchants, including Factory Direct Party and Oriental Trading. Some of the links on this site are affiliate links. If you click an affiliate link and make a qualifying purchase, we may earn a commission at no additional cost to you.",
      "",
      "## What this means",
      "- Commissions are paid by the merchant, not by you. Prices are set by the merchant and are the same whether or not you use our link.",
      "- Product availability, pricing, and promotions are controlled by the merchant and may change at any time.",
      "- We only recommend products we believe are relevant to your party. Our AI selects from a curated catalog; we do not rank merchants by commission rate.",
      "",
      "## FTC compliance",
      "This disclosure is made in accordance with the U.S. Federal Trade Commission's guidelines on the use of endorsements and testimonials in advertising. Affiliate relationships are disclosed prominently on every page that contains affiliate links, and in this permanent policy.",
      "",
      "## Your trust",
      "If you ever have a question about a recommendation or a link, please contact us. We would rather lose a commission than mislead you.",
    ].join("\n"),
  },
  {
    slug: "privacy",
    title: "Privacy Policy",
    body: [
      "## What we collect",
      "- **Hosts:** the email and name you provide when you create an account, and the party details you enter (theme, guest count, budget, and optionally a child's name and party date).",
      "- **Guests:** only the name and RSVP details you submit on an event page. Guests never create an account.",
      "- **Usage data:** we log clicks on product links to attribute purchases to parties. IP addresses are stored only as a one-way hash and are never retained in plain text.",
      "",
      "## Children's privacy (COPPA)",
      "This service collects information *about* children (such as age and party date) from their parents. Children are not users of the platform and do not create accounts. A child's name is optional, is never indexed by search engines, and never appears in a URL.",
      "",
      "## How we use data",
      "We use data to generate party plans, operate the registry and event pages, attribute affiliate conversions, and improve our recommendations. We do not sell your personal data.",
      "",
      "## Your choices",
      "You may request deletion of your account and associated data at any time by contacting us. Event pages are not indexed by search engines.",
      "",
      "## California residents (CCPA)",
      "California residents may request access to, or deletion of, their personal information. Contact us to exercise these rights.",
    ].join("\n"),
  },
  {
    slug: "terms",
    title: "Terms of Service",
    body: [
      "## Using PartyPlan",
      "By using this service you agree to use it lawfully and only for planning personal celebrations. You agree not to abuse the recommendation engine, attempt to access other users' data, or misuse affiliate links.",
      "",
      "## Product recommendations",
      "Product recommendations are generated by an automated system and are provided for informational purposes. We do not guarantee product availability, pricing, suitability, or merchant performance. All purchases are made directly with the merchant and are subject to the merchant's own terms and policies.",
      "",
      "## Affiliate links",
      "Some links are affiliate links as described in our Affiliate Disclosure. We comply with applicable disclosure laws and with each merchant's program terms.",
      "",
      "## Limitation of liability",
      "PartyPlan is provided \"as is\" without warranties of any kind. To the maximum extent permitted by law, we are not liable for any damages arising from your use of the service or from purchases made through linked merchants.",
      "",
      "## Changes",
      "We may update these terms from time to time. Continued use after changes constitutes acceptance.",
    ].join("\n"),
  },
];

export function getLegalDoc(slug: string) {
  return LEGAL_DOCS.find((d) => d.slug === slug) ?? null;
}
